spring.datasource.url=jdbc:postgresql://localhost:5432/document_processing_db
spring.datasource.username=postgres
spring.datasource.password=Mahesh@2026
openai.api.key=your_actual_openai_api_key_here
