spring.application.name=document-processing-pipeline
spring.datasource.url=jdbc:postgresql://localhost:5432/document_processing_db
spring.datasource.username=postgres
spring.datasource.password=admin
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
openai.api.key=${OPENAI_API_KEY}
springdoc.enable-kotlin=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB